# Generated by Django 2.2 on 2019-07-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190713_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_name',
            field=models.CharField(choices=[('N', 'New'), ('P', 'Prime'), ('O', 'Out Of Stock')], default='New', max_length=1),
            preserve_default=False,
        ),
    ]
