# Generated by Django 2.2 on 2019-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_name',
            field=models.CharField(choices=[('New', 'New'), ('Prime', 'Prime'), ('Out Of Stock', 'Out Of Stock')], max_length=1),
        ),
    ]
