# Generated by Django 2.2 on 2019-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190715_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_name',
            field=models.CharField(choices=[('New', 'New'), ('Prime', 'Prime'), ('Out Of Stock', 'Out Of Stock')], max_length=12),
        ),
    ]
