# Generated by Django 2.2 on 2019-07-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190715_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default/default-dummy-image.jpg', null=True, upload_to='default/'),
        ),
    ]
